install.packages("vscDebugger", repos = "https://manuelhentschel.r-universe.dev")
install.packages("tidyverse")
install.packages("janitor")
install.packages("fastLink")
install.packages("utf8")
install.packages("scales")